[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "WHATSAPP_NOTIFY_NUMBER,CORS_ORIGIN,PORT"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200